#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK_PROFILE_LEVEL="minimal"   # minimal | standard | strict
source "${SCRIPT_DIR}/_lib.sh"

# --- Hook Audit Logging ---
_hook_log() {
    local code=$1
    local log="${HOME}/.claude/hook-audit.log"
    mkdir -p "$(dirname "$log")"
    local ts; ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    local proj; proj=$(git rev-parse --show-toplevel 2>/dev/null | xargs basename 2>/dev/null || echo "unknown")
    local file="${FILE_PATH:-}"
    local status
    if [ "$code" -eq 2 ]; then status="BLOCKED"
    elif [ "$code" -eq 0 ]; then status="OK"
    else status="WARN"; fi
    printf '{"ts":"%s","hook":"%s","status":"%s","file":"%s","project":"%s"}\n' "$ts" "check-config-protection" "$status" "$file" "$proj" >> "$log"
    local lines; lines=$(wc -l < "$log" 2>/dev/null || echo 0)
    if [ "$lines" -gt 500 ]; then local tmp="${log}.$$.tmp"; tail -n 500 "$log" > "$tmp" 2>/dev/null && mv "$tmp" "$log" 2>/dev/null; rm -f "$tmp"; fi
}
trap '_hook_log $?' EXIT
# --- End Hook Audit Logging ---
# Hook: Blocks modifications to project configuration files
# Protects: .asmdef, settings.json, .inputactions, packages config
# Steers Claude to fix code rather than weakening project config
# Receives JSON on stdin with tool_input.file_path

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
    exit 0
fi

FILENAME=$(basename "$FILE_PATH")
EXT="${FILENAME##*.}"

BLOCKED=false
REASON=""

# Assembly definition files — changing references or constraints breaks compile
# Exception: test assembly definitions (EditModeTest, PlayModeTest) may need precompiledReferences updates
if [ "$EXT" = "asmdef" ]; then
    if echo "$FILE_PATH" | grep -qiE "(EditModeTest|PlayModeTest)"; then
        : # test assembly — allowed
    elif [ ! -f "$FILE_PATH" ]; then
        # New file — safe to create. This hook's stated reason ("modifying them to
        # fix a compile error usually means the architecture is wrong") is about
        # EDITING existing wiring; creating a new assembly boundary is a plan-time
        # architectural decision, already gated by validate-plan-paths.sh +
        # ARCHITECTURE_GATE. Blocking creation here made an approved plan
        # unexecutable and pushed agents into `cat >` workarounds
        # (see check-write-via-bash.sh). Matches the create/edit split
        # guard-critical-files.sh already uses for Installer/EventBus/AppModules.
        :
    else
        BLOCKED=true
        REASON=".asmdef files define assembly boundaries and reference rules. Modifying them to fix a compile error usually means the architecture is wrong, not the config."
    fi
fi

# Claude Code settings — hooks and permissions should not be weakened to bypass errors
if [ "$FILENAME" = "settings.json" ] && echo "$FILE_PATH" | grep -q "\.claude/"; then
    BLOCKED=true
    REASON=".claude/settings.json controls hooks and permissions. Do not disable hooks to work around errors — fix the code instead."
fi

# Input action assets — generated C# class depends on this structure
if [ "$EXT" = "inputactions" ]; then
    BLOCKED=true
    REASON=".inputactions files define the Input System schema. The generated PlayerControls.cs depends on this. Edit via Unity Editor Inspector only."
fi

# Package manifest — dependency changes should be intentional
if [ "$FILENAME" = "manifest.json" ] && echo "$FILE_PATH" | grep -q "Packages/"; then
    BLOCKED=true
    REASON="Packages/manifest.json controls Unity package dependencies. Do not modify to work around errors — diagnose the root cause instead."
fi

# packages-lock.json — auto-generated, never edit manually
if [ "$FILENAME" = "packages-lock.json" ]; then
    BLOCKED=true
    REASON="packages-lock.json is auto-generated by Unity. Never edit manually — it will be overwritten and can corrupt package state."
fi

if [ "$BLOCKED" = true ]; then
    # Deny-then-allow gate for .asmdef EDITS only — the same mechanism
    # guard-critical-files.sh already applies to Installer/EventBus/AppModules.
    # Without it there is no path at all to land a legitimate, approved reference
    # change (e.g. adding a Framework logging assembly so an Editor tool can use
    # it): the write blocks identically forever, which is what pushes agents into
    # `cat >` workarounds (see check-write-via-bash.sh). Blocking once still
    # forces the investigation this hook exists to demand; blocking twice only
    # forces a bypass.
    #
    # settings.json, .inputactions, manifest.json and packages-lock.json keep the
    # hard block — those are not architecture decisions an agent should land on a
    # retry, and settings.json in particular must stay human-only.
    if [ "$EXT" = "asmdef" ]; then
        # Plan coverage releases the .asmdef gate only. settings.json,
        # .inputactions, manifest.json and packages-lock.json are never released
        # by coverage — disabling a hook to work around an error must stay closed,
        # and that is the failure this whole mechanism was written in response to.
        if unity_plan_covers "$FILE_PATH"; then
            exit 0
        fi

        # Restricted to the Director (depth 0), same reasoning as gateguard.sh:
        # deny-then-allow verifies nothing, so a subagent that merely retries would
        # pass a gate whose purpose is to surface an assembly-boundary change to a
        # human — and a subagent reports to the Director, not to the user. Inside a
        # subagent the block repeats, leaving "report upward" as the only route.
        # No staleness downgrade, for the reason spelled out in gateguard.sh: here
        # a 0 PASSES, so downgrading would restore the bypass.
        CFG_DEPTH=$(unity_subagent_depth)

        DENIED_FILE="${UNITY_HOOK_STATE_DIR}/config-asmdef-denied.txt"
        PASSED_FILE="${UNITY_HOOK_STATE_DIR}/config-asmdef-passed.txt"
        touch "$DENIED_FILE" "$PASSED_FILE"

        if [ "$CFG_DEPTH" -eq 0 ] && grep -qxF "$FILE_PATH" "$PASSED_FILE" 2>/dev/null; then
            exit 0
        fi

        if [ "$CFG_DEPTH" -eq 0 ] && grep -qxF "$FILE_PATH" "$DENIED_FILE" 2>/dev/null; then
            echo "$FILE_PATH" >> "$PASSED_FILE"
            exit 0
        fi

        [ "$CFG_DEPTH" -eq 0 ] && echo "$FILE_PATH" >> "$DENIED_FILE"
    fi

    echo "BLOCKED: Configuration file is protected from direct modification."
    echo ""
    echo "File: $FILE_PATH"
    echo "Reason: $REASON"
    echo ""
    echo "If you are trying to fix a compile error or runtime issue:"
    echo "  → Fix the C# code to comply with the existing config"
    echo "  → Do NOT relax config constraints to make errors go away"
    echo ""
    echo "If this change is intentional and you understand the impact, confirm with the developer."
    if [ "$EXT" = "asmdef" ]; then
        echo ""
        if [ "${CFG_DEPTH:-0}" -gt 0 ]; then
            echo "You are a SUBAGENT — retrying will NOT clear this block. Report BLOCKED"
            echo "with this message verbatim and let the Director decide."
            echo ""
            echo "DIRECTOR, if no subagent is running the depth counter has leaked:"
            echo "  echo 0 > \"\$CLAUDE_PROJECT_DIR\"/.claude/state/subagent-depth"
        else
            echo "Once you have confirmed the change is intentional and scoped, re-attempt"
            echo "the edit — it will pass this time. Do NOT route around this via Bash."
        fi
    fi
    exit 2
fi

exit 0
