#!/bin/bash

# --- Hook Audit Logging ---
_hook_log() {
    local code=$1
    local log="${HOME}/.claude/hook-audit.log"
    local ts; ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    local proj; proj=$(git rev-parse --show-toplevel 2>/dev/null | xargs basename 2>/dev/null || echo "unknown")
    local file="${FILE_PATH:-}"
    local status
    if [ "$code" -eq 2 ]; then status="BLOCKED"
    elif [ "$code" -eq 0 ]; then status="OK"
    else status="WARN"; fi
    printf '{"ts":"%s","hook":"%s","status":"%s","file":"%s","project":"%s"}\n' "$ts" "check-config-protection" "$status" "$file" "$proj" >> "$log"
    local lines; lines=$(wc -l < "$log" 2>/dev/null || echo 0)
    if [ "$lines" -gt 5000 ]; then tail -n 5000 "$log" > "${log}.tmp" && mv "${log}.tmp" "$log"; fi
}
trap '_hook_log $?' EXIT
# --- End Hook Audit Logging ---
# Hook: Blocks modifications to project configuration files
# Protects: .asmdef, settings.json, .inputactions, packages config
# Steers Claude to fix code rather than weakening project config
# Receives JSON on stdin with tool_input.file_path

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
    exit 0
fi

FILENAME=$(basename "$FILE_PATH")
EXT="${FILENAME##*.}"

BLOCKED=false
REASON=""

# Assembly definition files — changing references or constraints breaks compile
if [ "$EXT" = "asmdef" ]; then
    BLOCKED=true
    REASON=".asmdef files define assembly boundaries and reference rules. Modifying them to fix a compile error usually means the architecture is wrong, not the config."
fi

# Claude Code settings — hooks and permissions should not be weakened to bypass errors
if [ "$FILENAME" = "settings.json" ] && echo "$FILE_PATH" | grep -q "\.claude/"; then
    BLOCKED=true
    REASON=".claude/settings.json controls hooks and permissions. Do not disable hooks to work around errors — fix the code instead."
fi

# Input action assets — generated C# class depends on this structure
if [ "$EXT" = "inputactions" ]; then
    BLOCKED=true
    REASON=".inputactions files define the Input System schema. The generated PlayerControls.cs depends on this. Edit via Unity Editor Inspector only."
fi

# Package manifest — dependency changes should be intentional
if [ "$FILENAME" = "manifest.json" ] && echo "$FILE_PATH" | grep -q "Packages/"; then
    BLOCKED=true
    REASON="Packages/manifest.json controls Unity package dependencies. Do not modify to work around errors — diagnose the root cause instead."
fi

# packages-lock.json — auto-generated, never edit manually
if [ "$FILENAME" = "packages-lock.json" ]; then
    BLOCKED=true
    REASON="packages-lock.json is auto-generated by Unity. Never edit manually — it will be overwritten and can corrupt package state."
fi

if [ "$BLOCKED" = true ]; then
    echo "BLOCKED: Configuration file is protected from direct modification."
    echo ""
    echo "File: $FILE_PATH"
    echo "Reason: $REASON"
    echo ""
    echo "If you are trying to fix a compile error or runtime issue:"
    echo "  → Fix the C# code to comply with the existing config"
    echo "  → Do NOT relax config constraints to make errors go away"
    echo ""
    echo "If this change is intentional and you understand the impact, confirm with the developer."
    exit 2
fi

exit 0
