#!/usr/bin/env python3
"""Validate that the C# a command generates can actually compile in the assemblies it generates.

Why this exists
---------------
`_Framework/Logging/` and `_Framework/SaveLoadSystems/` shipped an `.asmdef` while the folders were
still empty. Both were written `noEngineReferences: true` with `references: []`, which was correct
for a folder with no code in it. When code landed in them on 2026-09-02 the asmdefs did not move:
`DLog.cs` calls `UnityEngine.Debug`, `LocalSaveLoadDal.cs` calls `Application.persistentDataPath`,
and `SaveLoadService.cs` does `using Framework.Logging` — three compile errors, in every project the
template would ever generate. Nothing caught it: bats measures a hook's exit code, and no content
hook reads a markdown command file looking for assembly coherence.

This script closes exactly that class: an assembly boundary that no longer matches the code inside
it. It does NOT type-check. A missing type, a typo, or a bad signature passes here and is caught
only by a real Unity compile — see `docs/PLAN_setup_compile_probe.md`.

Fails closed: an unparseable asmdef, a reference to an assembly that is neither generated nor
externally known, and "no blocks found" are all errors, never a silent pass.

Usage:
    validate-generated-asmdefs.py [markdown-file ...]      # default: .claude/commands/setup-project.md
Exit codes: 0 = clean, 2 = at least one finding, 1 = usage/IO error.
"""

import json
import os
import re
import sys

# Namespaces that need no explicit .asmdef reference: the BCL, the engine assemblies every
# asmdef gets unless it opts out via noEngineReferences, and packages Unity auto-references.
#
# `Newtonsoft` is here on evidence, not assumption: `FrameworkSaveLoadSystems` compiles with
# `references: ["FrameworkLogging"]` alone while `LocalSaveLoadDal.cs` does
# `using Newtonsoft.Json` — measured by `.claude/tests/setup-compile-probe/` 2026-09-02.
NO_REFERENCE_NEEDED = (
    "System", "UnityEngine", "UnityEditor", "Unity.", "Newtonsoft", "TMPro",
    "NUnit", "NSubstitute", "JetBrains",
)

# Package namespaces that DO require an explicit reference, mapped to the assembly that
# provides them. This map is the reason the validator is not just a project-internal check:
# a missing package reference compiles exactly as badly as a missing project one.
#
# Only add an entry the compile probe has actually proven. `VContainer` is here because the
# probe's first run failed with CS0246 on `using VContainer.Unity` in `EventBus.cs` while
# `FrameworkEvents` carried `references: []` — a bug that had shipped unnoticed, and that the
# earlier version of this script waved through by treating every package namespace as external.
PACKAGE_ASSEMBLIES = {
    "VContainer": "VContainer",
    "Cysharp.Threading.Tasks": "UniTask",
    "UnityEngine.InputSystem": "Unity.InputSystem",
}

# Reference names that are legitimately not generated by the markdown being scanned.
EXTERNAL_ASSEMBLIES = (
    "VContainer", "UniTask", "Unity.InputSystem", "Unity.Entities", "Unity.Transforms",
    "Unity.Burst", "Unity.Collections", "Unity.Mathematics", "UnityEngine.TestRunner",
    "UnityEditor.TestRunner",
)

HEADER = re.compile(r'^#### `([^`]+)`\n```(json|csharp)\n(.*?)\n```', re.M | re.S)
NAMESPACE = re.compile(r'^\s*namespace\s+([\w.]+)', re.M)
USING = re.compile(r'^\s*using\s+(?:static\s+)?([\w.]+)\s*;', re.M)
# `Foo = UnityEngine.Bar;` is an alias, not a dependency edge we can resolve by namespace.
USING_ALIAS = re.compile(r'^\s*using\s+\w+\s*=')
UNITY_ENGINE_USE = re.compile(r'\bUnityEngine\b')


def parse(path):
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    asmdefs, sources = {}, []
    for m in HEADER.finditer(text):
        vpath, kind, body = m.group(1), m.group(2), m.group(3)
        if kind == "json" and vpath.endswith(".asmdef"):
            folder = os.path.dirname(vpath)
            try:
                data = json.loads(body)
                data["__vpath__"] = vpath
                asmdefs[folder] = data
            except json.JSONDecodeError as exc:
                asmdefs[folder] = {"__error__": str(exc), "__path__": vpath}
        elif kind == "csharp" and vpath.endswith(".cs"):
            sources.append((vpath, body))
    return asmdefs, sources


def owner_of(vpath, asmdefs):
    """Longest matching folder prefix wins — Games/Ecs/ must beat Games/."""
    best = None
    folder = os.path.dirname(vpath)
    for asm_folder in asmdefs:
        if folder == asm_folder or folder.startswith(asm_folder + "/"):
            if best is None or len(asm_folder) > len(best):
                best = asm_folder
    return best


def package_assembly_for(ns):
    """Assembly that must be referenced for `using ns`, or None when none is required."""
    best = None
    for prefix, asm in PACKAGE_ASSEMBLIES.items():
        if ns == prefix or ns.startswith(prefix + "."):
            if best is None or len(prefix) > len(best[0]):
                best = (prefix, asm)
    return best[1] if best else None


def needs_no_reference(ns):
    if package_assembly_for(ns):
        return False   # a package entry wins over a broad engine prefix (UnityEngine.InputSystem)
    return any(ns == p.rstrip(".") or ns.startswith(p) for p in NO_REFERENCE_NEEDED)


def validate(path):
    findings = []
    asmdefs, sources = parse(path)

    if not asmdefs:
        return ["NO ASMDEF BLOCKS FOUND in %s — this is a failure, not a pass. Wrong file, or the "
                "'#### `path`' + fenced-json shape changed." % path]
    if not sources:
        return ["NO C# BLOCKS FOUND in %s — this is a failure, not a pass." % path]

    for folder, data in asmdefs.items():
        if "__error__" in data:
            findings.append("%s: asmdef is not valid JSON — %s" % (data["__path__"], data["__error__"]))
    if findings:
        return findings

    by_name = {d["name"]: f for f, d in asmdefs.items() if "name" in d}

    # A reference must name a generated assembly or a known external one.
    for folder, data in asmdefs.items():
        for ref in data.get("references") or []:
            if ref.startswith("GUID:"):
                continue
            if ref in by_name or ref in EXTERNAL_ASSEMBLIES or ref in PACKAGE_ASSEMBLIES.values():
                continue
            findings.append("%s: references '%s', which is neither generated here nor a known "
                            "external assembly" % (data.get("name", folder), ref))

    # Which generated assembly owns which namespace.
    ns_owner = {}
    for vpath, body in sources:
        folder = owner_of(vpath, asmdefs)
        if folder is None:
            continue
        name = asmdefs[folder].get("name")
        for ns in NAMESPACE.findall(body):
            ns_owner.setdefault(ns, name)

    for vpath, body in sources:
        folder = owner_of(vpath, asmdefs)
        if folder is None:
            continue  # file outside every generated assembly — not this script's subject
        asm = asmdefs[folder]
        name = asm.get("name", folder)
        refs = set(asm.get("references") or [])
        fname = os.path.basename(vpath)

        if asm.get("noEngineReferences") and UNITY_ENGINE_USE.search(body):
            findings.append("%s: uses UnityEngine, but assembly '%s' sets noEngineReferences: true"
                            % (fname, name))

        for line in body.splitlines():
            if USING_ALIAS.match(line):
                continue
            m = USING.match(line)
            if not m:
                continue
            ns = m.group(1)
            pkg = package_assembly_for(ns)
            if pkg:
                if pkg not in refs:
                    findings.append("%s: 'using %s' needs package assembly '%s', but '%s' does "
                                    "not reference it" % (fname, ns, pkg, name))
                continue
            if needs_no_reference(ns):
                continue
            target = ns_owner.get(ns)
            if target is None:
                # Walk up: `using A.B.C` is satisfied by an assembly owning `A.B`.
                parts = ns.split(".")
                while len(parts) > 1 and target is None:
                    parts.pop()
                    target = ns_owner.get(".".join(parts))
            if target is None or target == name:
                continue
            if target not in refs:
                findings.append("%s: 'using %s' resolves to assembly '%s', but '%s' does not "
                                "reference it" % (fname, ns, target, name))

    return findings


def extract(path, out_dir, project_name="Probe", skips=()):
    """Materialise every generated block onto disk under out_dir.

    Shared with `.claude/tests/setup-compile-probe/` on purpose: the probe must compile exactly
    the files this validator reasons about. Two parsers would eventually disagree about what
    "the generated files" are, and the disagreement would surface as a green probe over an
    unchecked file.
    """
    asmdefs, sources = parse(path)
    written = []
    items = []
    for folder, data in asmdefs.items():
        if "__error__" in data:
            raise ValueError("asmdef is not valid JSON: %s" % data["__path__"])
        items.append((data["__vpath__"], json.dumps(data_clean(data), indent=4)))
    items.extend(sources)

    for vpath, body in items:
        if any(sk in vpath for sk in skips):
            continue
        real = os.path.join(out_dir, vpath.replace("[ProjectName]", project_name))
        os.makedirs(os.path.dirname(real), exist_ok=True)
        with open(real, "w", encoding="utf-8") as fh:
            fh.write(body.replace("[ProjectName]", project_name) + "\n")
        written.append(real)
    return written


def data_clean(d):
    return {k: v for k, v in d.items() if not k.startswith("__")}


def main(argv):
    if "--extract" in argv:
        i = argv.index("--extract")
        out = argv[i + 1]
        rest = argv[1:i] + argv[i + 2:]
        name = "Probe"
        skips = []
        while "--project-name" in rest:
            j = rest.index("--project-name"); name = rest[j + 1]; rest = rest[:j] + rest[j + 2:]
        while "--skip" in rest:
            j = rest.index("--skip"); skips.append(rest[j + 1]); rest = rest[:j] + rest[j + 2:]
        src = rest[0] if rest else ".claude/commands/setup-project.md"
        try:
            files = extract(src, out, name, tuple(skips))
        except (OSError, ValueError) as exc:
            print("ERROR: %s" % exc, file=sys.stderr)
            return 1
        if not files:
            print("ERROR: extracted 0 files from %s — that is a failure, not a pass." % src,
                  file=sys.stderr)
            return 1
        for f in files:
            print(f)
        return 0

    paths = argv[1:] or [".claude/commands/setup-project.md"]
    total = []
    for p in paths:
        if not os.path.isfile(p):
            print("ERROR: not a file: %s" % p, file=sys.stderr)
            return 1
        found = validate(p)
        if found:
            print("FAIL %s" % p)
            for f in found:
                print("  %s" % f)
        else:
            print("OK   %s" % p)
        total.extend(found)
    if total:
        print("\n%d finding(s). An assembly boundary no longer matches the code inside it."
              % len(total))
        print("This script does not type-check — a clean run is not a compile.")
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
