#!/usr/bin/env bash
# Measures the Blender -> FBX -> Unity contract end to end, against a real Unity Editor.
#
# WHY A GENERATOR AND NOT COMMITTED FIXTURES:
# the inputs are .fbx meshes and the harness is a Unity project. A committed .fbx is an
# unreviewable binary blob — a diff cannot show that a vertex moved — and a committed Unity
# project is 13 MB of Library/ per run. Both are rebuilt from bpy primitives every time, so
# the thing under test is always the CURRENT export contract in
# .claude/scripts/blender-mcp-bridge.py, never a snapshot of an older one.
#
# WHY IT EXISTS AT ALL:
# measured 2026-08-22 — a check that only asserted world bounds passed all four
# apply_scale_options values, including the two that import with a scale=100 root and a
# 270.020 deg rotation. Asserting size alone is decoration. This harness asserts world
# size AND root scale AND root euler AND mesh/material/bone counts. See SKILL.md Card 5a.
#
# Usage:
#   .claude/tests/blender-fbx-probe/run-probe.sh [--keep] [--case NAME]... [--unity PATH]
#
#   --keep         leave the throwaway Unity project on disk and print its path
#   --case NAME    run only this case (repeatable): static_box parented multi_mesh
#                  two_materials skinned
#   --unity PATH   Unity executable; default is the newest 6000.* under
#                  /Applications/Unity/Hub/Editor
#
# Prerequisites: Blender running with the official MCP add-on (see
# .claude/skills/third-party/blender-mcp/SKILL.md), on an EMPTY unsaved file — the harness
# clears the scene and refuses to run if a file is open or dirty. Plus a Unity 6 Editor.
#
# Exit 0 = every assertion passed. Exit 1 = at least one FAIL. Exit 2 = could not run.
# Neither Blender nor this script ever saves a .blend.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../../.." && pwd)"

KEEP=0
UNITY=""
CASE_ARGS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --keep)  KEEP=1; shift ;;
        --case)  CASE_ARGS+=(--case "$2"); shift 2 ;;
        --unity) UNITY="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,/^set -uo/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//; $d'
            exit 0 ;;
        *) echo "unknown argument: $1 (try --help)" >&2; exit 2 ;;
    esac
done

if [[ -z "$UNITY" ]]; then
    UNITY="$(ls -d /Applications/Unity/Hub/Editor/6000.* 2>/dev/null | sort -V | tail -1)/Unity.app/Contents/MacOS/Unity"
fi
if [[ ! -x "$UNITY" ]]; then
    echo "Unity executable not found: $UNITY  (pass --unity PATH)" >&2
    exit 2
fi

WORK="$(mktemp -d)"
PROJ="$WORK/FbxProbeProject"
trap '[[ $KEEP -eq 1 ]] || rm -rf "$WORK"' EXIT

echo "== 1/3  Blender: build cases and export via the real tool"
python3 "$HERE/build-cases.py" --outdir "$WORK/fbx" "${CASE_ARGS[@]+"${CASE_ARGS[@]}"}" || exit 2

echo
echo "== 2/3  Unity: throwaway project ($(basename "$(dirname "$(dirname "$(dirname "$UNITY")")")"))"
"$UNITY" -batchmode -nographics -createProject "$PROJ" -quit -logFile "$WORK/create.log" >/dev/null 2>&1 \
    || { echo "createProject failed; see $WORK/create.log" >&2; KEEP=1; exit 2; }

mkdir -p "$PROJ/Assets/Editor" "$PROJ/Assets/Models" "$PROJ/Assets/StreamingAssets"
cp "$WORK"/fbx/*.fbx "$PROJ/Assets/Models/" 2>/dev/null
cp "$WORK/fbx/cases.json" "$PROJ/Assets/StreamingAssets/cases.json"

cat > "$PROJ/Assets/Editor/FbxProbe.cs" <<'CSEOF'
// Generated by .claude/tests/blender-fbx-probe/run-probe.sh — do not commit.
// Reads StreamingAssets/cases.json and asserts each case's expectations against the real
// import result. Deliberately asserts root scale and euler, not only world bounds: a
// bounds-only check passes imports that carry a scale=100 root (SKILL.md Card 5a).
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

public static class FbxProbe
{
    [System.Serializable]
    private class Case
    {
        public string name;
        public string fbx;
        public string export_status;
        public string note;
        public bool build_failed;
        public bool expect_refused;
        public float[] world;
        public float[] root_scale;
        public float[] root_euler;
        public float euler_tol;
        public int mesh_count = -1;
        public int material_count = -1;
        public int bone_count = -1;
        public float child_world_y = float.NaN;
    }

    [System.Serializable]
    private class Manifest { public Case[] cases; }

    private static int _pass, _fail;

    public static void Run()
    {
        var sb = new StringBuilder();
        sb.AppendLine("###PROBE_BEGIN");

        var json = File.ReadAllText(Path.Combine(Application.streamingAssetsPath, "cases.json"));
        var manifest = JsonUtility.FromJson<Manifest>(json);

        foreach (var c in manifest.cases)
        {
            sb.AppendLine();
            sb.AppendLine($"CASE {c.name}");
            if (!string.IsNullOrEmpty(c.note)) sb.AppendLine($"     note: {c.note}");

            if (c.build_failed) { Fail(sb, "blender build", "case never built"); continue; }
            if (c.expect_refused)
            {
                Check(sb, "export refused as expected", c.export_status == "refused", c.export_status);
                continue;
            }
            Check(sb, "export status ok", c.export_status == "ok", c.export_status);
            if (c.export_status != "ok") continue;

            AssetDatabase.ImportAsset(c.fbx, ImportAssetOptions.ForceUpdate);
            var asset = AssetDatabase.LoadAssetAtPath<GameObject>(c.fbx);
            if (asset == null) { Fail(sb, "import produced a GameObject", "null"); continue; }

            EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            var inst = (GameObject)PrefabUtility.InstantiatePrefab(asset);
            inst.transform.position = Vector3.zero;
            inst.transform.rotation = Quaternion.identity;

            var renderers = inst.GetComponentsInChildren<Renderer>();
            var filters = inst.GetComponentsInChildren<MeshFilter>();
            var skinned = inst.GetComponentsInChildren<SkinnedMeshRenderer>();

            if (c.root_scale != null)
                Check(sb, "root localScale", Near(inst.transform.localScale, V(c.root_scale), 1e-4f),
                      F(inst.transform.localScale));
            if (c.root_euler != null)
            {
                var tol = c.euler_tol > 0f ? c.euler_tol : 1e-3f;
                Check(sb, $"root euler (tol {tol})", Near(inst.transform.localEulerAngles, V(c.root_euler), tol),
                      F(inst.transform.localEulerAngles));
            }
            if (c.world != null && renderers.Length > 0)
            {
                var b = renderers[0].bounds;
                for (var i = 1; i < renderers.Length; i++) b.Encapsulate(renderers[i].bounds);
                Check(sb, "world bounds size", Near(b.size, V(c.world), 1e-3f), F(b.size));
            }
            if (c.mesh_count >= 0)
            {
                var n = filters.Length + skinned.Length;
                Check(sb, $"mesh count == {c.mesh_count}", n == c.mesh_count, n.ToString());
            }
            if (c.material_count >= 0)
            {
                var mats = new HashSet<Material>();
                foreach (var r in renderers)
                    foreach (var mat in r.sharedMaterials)
                        if (mat != null) mats.Add(mat);
                // 0 means "no material authored" — Unity substitutes a default, so accept <= 1.
                var ok = c.material_count == 0 ? mats.Count <= 1 : mats.Count == c.material_count;
                Check(sb, $"material count == {c.material_count}", ok, mats.Count.ToString());
            }
            if (c.bone_count >= 0)
            {
                var bones = skinned.Sum(s => s.bones?.Length ?? 0);
                Check(sb, $"skinned bone count == {c.bone_count}", bones == c.bone_count, bones.ToString());
            }
            if (!float.IsNaN(c.child_world_y) && filters.Length > 0)
            {
                var y = filters[0].transform.position.y;
                Check(sb, $"child world Y == {c.child_world_y}", Mathf.Abs(y - c.child_world_y) < 1e-3f,
                      y.ToString("F3"));
            }
        }

        sb.AppendLine();
        sb.AppendLine($"TOTAL: {_pass} pass, {_fail} fail");
        sb.AppendLine("###PROBE_END");
        Debug.Log(sb.ToString());
        EditorApplication.Exit(_fail == 0 ? 0 : 1);
    }

    private static void Check(StringBuilder sb, string what, bool ok, string got)
    {
        if (ok) _pass++; else _fail++;
        sb.AppendLine($"  [{(ok ? "PASS" : "FAIL")}] {what,-34} got {got}");
    }

    private static void Fail(StringBuilder sb, string what, string got) => Check(sb, what, false, got);
    private static bool Near(Vector3 a, Vector3 b, float tol) => Vector3.Distance(a, b) < tol;
    private static Vector3 V(float[] a) => new Vector3(a[0], a[1], a[2]);
    private static string F(Vector3 v) => $"({v.x:F3},{v.y:F3},{v.z:F3})";
}
CSEOF

echo "== 3/3  Unity: import and assert"
"$UNITY" -batchmode -nographics -projectPath "$PROJ" -executeMethod FbxProbe.Run -logFile "$WORK/probe.log" >/dev/null 2>&1
UNITY_EXIT=$?

echo
if ! sed -n '/###PROBE_BEGIN/,/###PROBE_END/p' "$WORK/probe.log"; then
    echo "no probe output — compile error or crash. Log tail:" >&2
    grep -iE "CS[0-9]{4}|Exception|error CS" "$WORK/probe.log" | head -20 >&2
    KEEP=1
    exit 2
fi

[[ $KEEP -eq 1 ]] && echo && echo "kept: $PROJ" && echo "log:  $WORK/probe.log"
exit $UNITY_EXIT
